//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQNWebsiteUI.Models.EQNDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.ArticleImages = new HashSet<ArticleImage>();
        }
    
        public int ArticleId { get; set; }
        public string ArticleText { get; set; }
        public int UserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime PublishedDate { get; set; }
    
        public virtual ICollection<ArticleImage> ArticleImages { get; set; }
    }
}
