//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQNWebsiteUI.Models.EQNDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserWidget
    {
        public UserWidget()
        {
            this.WidgetSettings = new HashSet<WidgetSetting>();
        }
    
        public int UserWidgetId { get; set; }
        public int UserId { get; set; }
        public int WidgetId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Widget Widget { get; set; }
        public virtual ICollection<WidgetSetting> WidgetSettings { get; set; }
    }
}
