//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQNWebsiteUI.Models.EQNDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WidgetType
    {
        public WidgetType()
        {
            this.Widgets = new HashSet<Widget>();
        }
    
        public int WidgetTypeId { get; set; }
        public string WidgetTypeName { get; set; }
        public string WidgetTooltip { get; set; }
        public string WidgetDescription { get; set; }
    
        public virtual ICollection<Widget> Widgets { get; set; }
    }
}
