//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParseExcelToChapters.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chapter
    {
        public Chapter()
        {
            this.Pages = new HashSet<Page>();
            this.Owners = new HashSet<UserChapter>();
        }
    
        public int ChapterId { get; set; }
        public int StoryId { get; set; }
        public decimal Price { get; set; }
        public int FirstPageId { get; set; }
    
        public virtual ICollection<Page> Pages { get; set; }
        public virtual Page FirstPage { get; set; }
        public virtual ICollection<UserChapter> Owners { get; set; }
        public virtual Story Story { get; set; }
    }
}
