//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParseExcelToChapters.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class StoryBuildsEntities : DbContext
    {
        public StoryBuildsEntities()
            : base("name=StoryBuildsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Chapter> Chapters { get; set; }
        public DbSet<Choice> Choices { get; set; }
        public DbSet<Page> Pages { get; set; }
        public DbSet<Story> Stories { get; set; }
    
        public virtual ObjectResult<Nullable<int>> InsertStory(string storyName, Nullable<decimal> storyPrice)
        {
            var storyNameParameter = storyName != null ?
                new ObjectParameter("StoryName", storyName) :
                new ObjectParameter("StoryName", typeof(string));
    
            var storyPriceParameter = storyPrice.HasValue ?
                new ObjectParameter("StoryPrice", storyPrice) :
                new ObjectParameter("StoryPrice", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("InsertStory", storyNameParameter, storyPriceParameter);
        }
    }
}
