//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace importChapters.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StoryBuildsContainer : DbContext
    {
        public StoryBuildsContainer()
            : base("name=StoryBuildsContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<User> Users { get; set; }
        public DbSet<UserChapter> UserChapters { get; set; }
        public DbSet<Chapter> Chapters { get; set; }
        public DbSet<Story> Stories { get; set; }
        public DbSet<Page> Pages { get; set; }
        public DbSet<Choice> Choices { get; set; }
    }
}
