//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace importChapters.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.OwnedChapters = new HashSet<UserChapter>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<UserChapter> OwnedChapters { get; set; }
    }
}
