//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParseExcelToChapters.Model
{
    using System;
    
    public enum PageType : int
    {
        Dialogue = 0,
        Monologue = 1,
        Mini_Game = 2
    }
}
