//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParseExcelToChapters.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Story
    {
        public Story()
        {
            this.Chapters = new HashSet<Chapter>();
        }
    
        public int StoryId { get; set; }
        public string StoryName { get; set; }
        public decimal Price { get; set; }
    
        public virtual ICollection<Chapter> Chapters { get; set; }
    }
}
