//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQNWebsiteUI.Models.EQNDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EQNDBModelEntities : DbContext
    {
        public EQNDBModelEntities()
            : base("name=EQNDBModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<User> Users { get; set; }
        public DbSet<Image> Images { get; set; }
        public DbSet<Article> Articles { get; set; }
        public DbSet<ArticleImage> ArticleImages { get; set; }
        public DbSet<Widget> Widgets { get; set; }
        public DbSet<WidgetType> WidgetTypes { get; set; }
        public DbSet<UserWidget> UserWidgets { get; set; }
        public DbSet<WidgetSetting> WidgetSettings { get; set; }
    }
}
