//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQNWebsiteUI.Models.EQNDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public Image()
        {
            this.ArticleImages = new HashSet<ArticleImage>();
        }
    
        public int ImageId { get; set; }
        public string ImageName { get; set; }
        public string ImageLocation { get; set; }
        public byte[] Binary { get; set; }
        public int UserId { get; set; }
    
        public virtual ICollection<ArticleImage> ArticleImages { get; set; }
        public virtual User User { get; set; }
    }
}
