//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQNWebsiteUI.Models.EQNDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Images = new HashSet<Image>();
            this.UserWidgets = new HashSet<UserWidget>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<Image> Images { get; set; }
        public virtual ICollection<UserWidget> UserWidgets { get; set; }
    }
}
