//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQNWebsiteUI.Models.EQNDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WidgetSetting
    {
        public int WidgetSettingId { get; set; }
        public int UserWidgetId { get; set; }
        public string SettingName { get; set; }
        public string SettingValue { get; set; }
    
        public virtual UserWidget UserWidget { get; set; }
    }
}
